### ISSUE TITLE
Komunikat Error: Class 'GusApi\Adapter\Soap\SoapAdapter' not found in /xxxxxx.pl/controllers/SiteController.php:2028

### ISSUE THREAD

**Issue by KrychuM** [johnzuk/GusApi#104]
Witam,

Próbuje ściągnąć dane z GUS do witryny postawionej na YII2. Pojawia mi się następujący komunikat:
Error: Class 'GusApi\Adapter\Soap\SoapAdapter' not found in /xxxxxx.pl/controllers/SiteController.php:2028
Stack trace:
#0 [internal function]: app\controllers\SiteController->actionLoadGus('773-105-74-03')
#1 /xxxxxx.pl/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /xxxxxx.pl/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /xxxxxx.pl/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('load-gus', Array)
#4 /xxxxxx.pl/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('site/load-gus', Array)
#5 /xxxxxx.pl/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#6 /xxxxxx.pl/web/index.php(23): yii\base\Application->run()
#7 {main}

Oto funkcja której zadaniem jest zwrócenie wyniku. 
`    public function actionLoadGus( $nip )
    {
      $firmname = '';
      $address  = '';
      $city     = '';
      $error    = '';
      
      $gus = new GusApi(Yii::$app->params[ 'guskey' ],
        new \GusApi\Adapter\Soap\SoapAdapter(
          RegonConstantsInterface::BASE_WSDL_URL_TEST,
          RegonConstantsInterface::BASE_WSDL_ADDRESS_TEST
          ));
      //for development server use:
      //$gus = new GusApi('abcde12345abcde12345', 'dev');
      
      try {
        $nipToCheck = $nip; //change to valid nip value
        $gus->login();
      
        $gusReports = $gus->getByNip($nipToCheck);
      
        $error = $gus->dataStatus();
 
        foreach ($gusReports as $gusReport) {
          //you can change report type to other one
          // $reportType = ReportTypes::REPORT_PERSON;
          $firmname = $gusReport->getName();
          $address = $gusReport->getStreet(). ' ' . $gusReport->getPropertyNumber() . '/' . $gusReport->getApartmentNumber();
          $city = $gusReport->getCity();
        }
      } catch (InvalidUserKeyException $e) {
          $error = 'Bad user key';
      } catch (NotFoundException $e) {
          $error =  'No data found <br>';
          $error .= 'For more information read server message below: <br>';
          $error .= $gus->getResultSearchMessage();
      }
      
      return $this->renderContent( json::encode( array(
        'firmname'  => $firmname,
        'address'   => $address,
        'city'      => $city,
        'error'     => $error
      )));
    }
`

Za wszelką pomoc w rozwiązaniu powyższego błędu z góry dziękuję.

Pozdrawiam

**Comment by IonBazan** [comment]
Zapomniałeś prawdopodobnie przekopiować katalog `vendor` po instalacji `gusapi/gusapi`
