### ISSUE TITLE
Problem po sobotnich pracach modernizacyjnych

### ISSUE THREAD

**Issue by KR2615** [johnzuk/GusApi#70]
Witajcie.

W sobotę GUS wystosował następującego e-maila:

> Szanowni Państwo,

> niniejsza korespondencja dotyczy Usługi BIR1 (Baza Internetowa REGON) – usługi sieciowej udostępniającej dane z rejestru REGON
> ( http://bip.stat.gov.pl/dzialalnosc-statystyki-publicznej/rejestr-regon/interfejsyapi/informacje-ogolne/ ),
> w której posiadają Państwo konto dostępowe, a Państwa adres email został wskazany jako adres osoby do kontaktu.
> 
> Informujemy, że ze względu na planowane prace modernizacyjne w dniu 01.12.2018 (sobota), w godz. 12:00 - 18:00,
> 
> mogą wystąpić krótkotrwałe przerwy w działaniu Usługi BIR1.
> (Dotyczy także wyszukiwarki „on-line”: https://wyszukiwarkaregon.stat.gov.pl/appBIR/index.aspx ).
> 
> 
> Przepraszamy za potencjalne niedogodności z tego powodu.
> 
> Jeśli posiadany przez nas adres osoby do kontaktu jest nieaktualny prosimy o informację zwrotną z aktualnymi danymi dot. osoby do kontaktu.
> 

Po tym wydarzeniu gusapi zwraca u mnie:

`<br />
<b>Fatal error</b>:  Uncaught SoapFault exception: [HTTP] Error Fetching http headers in /path/GUS/vendor/gusapi/gusapi/src/GusApi/Client/SoapClient.php:51
Stack trace:
#0 /path/GUS/vendor/gusapi/gusapi/src/GusApi/Client/SoapClient.php(51): SoapClient-&gt;__doRequest('&lt;?xml version=&quot;...', 'https://wyszuki...', 'http://CIS/BIR/...', 2, 0)
#1 [internal function]: GusApi\Client\SoapClient-&gt;__doRequest('&lt;?xml version=&quot;...', 'https://wyszuki...', 'http://CIS/BIR/...', 2, 0)
#2 /path/GUS/vendor/gusapi/gusapi/src/GusApi/Adapter/Soap/SoapAdapter.php(70): SoapClient-&gt;__call('Zaloguj', Array)
#3 /path/GUS/vendor/gusapi/gusapi/src/GusApi/Adapter/Soap/SoapAdapter.php(70): GusApi\Client\SoapClient-&gt;Zaloguj(Array)
#4 /path/GUS/vendor/gusapi/gusapi/src/GusApi/GusApi.php(68): GusApi\Adapter\Soap\So in <b>/path/GUS/vendor/gusapi/gusapi/src/GusApi/Client/SoapClient.php</b> on line <b>51</b><br />
`
Czy u Was też to występuję?

**Comment by johnzuk** [comment]
Wygląda na to, że usługa produkcyjna odpowiada bardzo wolno i mamy timeout. Testowałem przed chwilą i średni czas odpowiedzi serwera to ~ 95s. Przy ustawionym timeoucie rzędu 100s requesty przechodzą ale jest to nieznośnie wolne. 
Zrzut z SoapUI:
![zrzut ekranu z 2018-12-03 22-36-36](https://user-images.githubusercontent.com/5394761/49403053-fa5ff280-f74b-11e8-9df7-41eb5f368930.png)
Wydaje mi się, że w tej sytuacji jedyne co można zrobić to czekać aż serwer zacznie działać normalnie.
Zmian w dokumentacji żadnych nie widzę więc teoretycznie wszystko inne powinno działać.
